openapi: 3.0.0
info:
  title: Bitcoin Transaction Data API
  description: API for retrieving Bitcoin transaction data
  version: 1.0.0
servers:
  - url: https://example.com/api/v1
paths:
  /bitcoin/transactions:
    get:
      summary: Retrieve Bitcoin transaction data
      parameters:
        - name: network
          in: query
          description: Name of the cryptocurrency network
          required: true
          schema:
            type: string
            example: bitcoin
        - name: from
          in: query
          description: Start date for data retrieval (format: YYYY-MM-DD)
          required: true
          schema:
            type: string
            format: date
            example: "2024-03-12"
        - name: till
          in: query
          description: End date for data retrieval (format: YYYY-MM-DD)
          required: true
          schema:
            type: string
            format: date-time
            example: "2024-03-19T23:59:59"
        - name: dateFormat
          in: query
          description: Date format for response dates
          required: true
          schema:
            type: string
            example: "%Y-%m-%d"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      bitcoin:
                        type: object
                        properties:
                          transactions:
                            type: array
                            items:
                              type: object
                              properties:
                                date:
                                  type: object
                                  properties:
                                    date:
                                      type: string
                                      example: "2024-03-12"
                                count:
                                  type: string
                                  example: "341867"
                                feeValue:
                                  type: number
                                  format: float
                                  example: 38.60291378
                                avgFee:
                                  type: number
                                  format: float
                                  example: 0.00011291
        '400':
          description: Bad request
        '500':
          description: Internal server error
